name: r8it
description: Raite it app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: any
  bloc: ^8.1.0
  flutter_bloc: ^8.0.0
  dio: ^5.3.3
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Montserrat-Thin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
  generate: true
  uses-material-design: true
