name: r8it
description: Raite it app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: any
  bloc: ^8.1.0
  flutter_bloc: ^8.0.0
  dio: ^5.3.3
  json_annotation: ^4.8.1
  rit_client:
    path: rit_client
  camera: ^0.10.5+7
  path_provider: ^2.1.1
  path: ^1.8.3
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat-Black.ttf
        style: normal
        weight: 900
      - asset: assets/fonts/Montserrat-BlackItalic.ttf
        style: italic
        weight: 900
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        style: normal
        weight: 800
      - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        style: italic
        weight: 800
      - asset: assets/fonts/Montserrat-Bold.ttf
        style: normal
        weight: 700
      - asset: assets/fonts/Montserrat-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        style: normal
        weight: 600
      - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        style: italic
        weight: 600
      - asset: assets/fonts/Montserrat-Medium.ttf
        style: normal
        weight: 500
      - asset: assets/fonts/Montserrat-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: assets/fonts/Montserrat-Italic.ttf
        style: italic
        weight: 400
      - asset: assets/fonts/Montserrat-Regular.ttf
        style: normal
        weight: 400
      - asset: assets/fonts/Montserrat-Light.ttf
        style: normal
        weight: 300
      - asset: assets/fonts/Montserrat-LightItalic.ttf
        style: italic
        weight: 300
      - asset: assets/fonts/Montserrat-ExtraLight.ttf
        style: normal
        weight: 200
      - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        style: italic
        weight: 200
      - asset: assets/fonts/Montserrat-Thin.ttf
        style: normal
        weight: 100
      - asset: assets/fonts/Montserrat-ThinItalic.ttf
        style: italic
        weight: 100
  generate: true
  uses-material-design: true
